export const responseConstants = {
    createSuccess: 'Create was successful',
    deleteSuccess: 'Delete was successful',
    updateSuccess: 'Update was successful',
    forbidden: 'Forbidden',
    companyAlreadyExist: 'Company with this email already exist!',
    hotelAlreadyExists: 'Hotel with this name already exist!',
    ownerMustHaveOneCompany: 'Company with this owner already exist!',
    hotelNotFound: 'Hotel not found',
    companyNotFound: 'Your Company not found',
    arrayServiceOrRoomEmpty: 'Services and Rooms array can`t be empty',
    serviceIdCantBeNull: 'Service id can`t be null',
    notOwnerOfHotel: ' You are not owner of this hotel!',
    logoutSuccess: 'Logout was successful!',
    ok: 'Ok!',
};
